### ISSUE TITLE
# moisture over 100 procent IndexError: index out of range

### ISSUE THREAD

**Issue by fhb** [ThomDietrich/miflora-mqtt-daemon#144]
Hi, i just installed Mosquito and the miflora daemon, then added username and password for the mqtt daemon and three [square Bluetooth temperature/humidity sensors](https://www.amazon.de/Xiaomi-NUN4126GL-Temperatur-Feuchtigkeitsmonitor-weiß/dp/B08C7KVDJW/ref=asc_df_B08C7KVDJW/?tag=googshopde-21&linkCode=df0&hvadid=474157245964&hvpos=&hvnetw=g&hvrand=14216068557397986842&hvpone=&hvptwo=&hvqmt=&hvdev=c&hvdvcmdl=&hvlocint=&hvlocphy=9044404&hvtargid=pla-981132504859&psc=1&th=1&psc=1). For every single one of them I get the following error:

```
openhabian@openhab:/opt/miflora-mqtt-daemon $ python3 /opt/miflora-mqtt-daemon/miflora-mqtt-daemon.py

Xiaomi Mi Flora Plant Sensor MQTT Client/Daemon
Source: https://github.com/ThomDietrich/miflora-mqtt-daemon

[2021-06-06 21:08:04] Connecting to MQTT broker ...
[2021-06-06 21:08:04] MQTT connection established

Adding sensor to device list and testing connection ...
Name:          "3DPrinterEnclosure"
Traceback (most recent call last):
  File "/opt/miflora-mqtt-daemon/miflora-mqtt-daemon.py", line 206, in <module>
    flora_poller.fill_cache()
  File "/usr/local/lib/python3.7/dist-packages/miflora/miflora_poller.py", line 119, in fill_cache
    self._check_data()
  File "/usr/local/lib/python3.7/dist-packages/miflora/miflora_poller.py", line 204, in _check_data
    if self._cache[7] > 100:  # moisture over 100 procent
IndexError: index out of range
```

**Comment by fhb** [comment]
Overlooked that the sensors are not supported and the daemon is limited to only one type of sensor. Sorry.
