### ISSUE TITLE
cannot import name 'init'

### ISSUE THREAD

**Issue by jruben4** [ThomDietrich/miflora-mqtt-daemon#48]
On a clean install of rasbian, I am getting this error when I run miflora:

pi@raspberrypi:~ $ python3 /opt/miflora-mqtt-daemon/miflora-mqtt-daemon.py
Traceback (most recent call last):
  File "/opt/miflora-mqtt-daemon/miflora-mqtt-daemon.py", line 11, in <module>
    from colorama import init as colorama_init
ImportError: cannot import name 'init'

**Comment by ThomDietrich** [comment]
Did you install the requirements?

https://github.com/ThomDietrich/miflora-mqtt-daemon#installation

**Comment by jruben4** [comment]
Yes:

**pi@raspberrypi:/opt/miflora-mqtt-daemon $** sudo pip3 install -r requirements.txt
Requirement already satisfied: miflora==0.4 in /usr/local/lib/python3.5/dist-packages (from -r requirements.txt (line 2))
Requirement already satisfied: paho-mqtt==1.3.0 in /usr/local/lib/python3.5/dist-packages (from -r requirements.txt (line 3))
Requirement already satisfied: wheel==0.29.0 in /usr/lib/python3/dist-packages (from -r requirements.txt (line 4))
Requirement already satisfied: sdnotify==0.3.1 in /usr/local/lib/python3.5/dist-packages (from -r requirements.txt (line 5))
Requirement already satisfied: colorama==0.3.9 in /usr/local/lib/python3.5/dist-packages (from -r requirements.txt (line 6))
Requirement already satisfied: Unidecode==0.4.21 in /usr/local/lib/python3.5/dist-packages (from -r requirements.txt (line 7))

**pi@raspberrypi:/opt/miflora-mqtt-daemon $** python3 /opt/miflora-mqtt-daemon/miflora-mqtt-daemon.py
Traceback (most recent call last):
  File "/opt/miflora-mqtt-daemon/miflora-mqtt-daemon.py", line 11, in <module>
    from colorama import init as colorama_init
ImportError: cannot import name 'init'

**Comment by ThomDietrich** [comment]
Has to be some versions or dependencies issue. Not sure what's going on. My best bet: Update your system packages and pip3 packages

**Comment by ThomDietrich** [comment]
It does. In fact it was mostly tested there. The error is unknown to me, hence my suspicion that the error is related to your specific system.

**Comment by jruben4** [comment]
Ok, redid the whole setup again and it worked.  I spell it out below more as an FYI since some commands need to be sudo'd that weren't indicated in the readme.

clean raspbian-stretch-lite 4-8-18
setup ssh
change passwd
setup wifi

sudo apt-get update

sudo apt install git python3 python3-pip bluetooth bluezgit clone 

git clone https://github.com/ThomDietrich/miflora-mqtt-daemon.git /opt/miflora-mqtt-daemon ---> permission denied

sudo git clone https://github.com/ThomDietrich/miflora-mqtt-daemon.git /opt/miflora-mqtt-daemon

cd /opt/miflora-mqtt-daemon

sudo pip3 install -r requirements.txt

cp /opt/miflora-mqtt-daemon/config.{ini.dist,ini} ----> permission denied

sudo cp /opt/miflora-mqtt-daemon/config.{ini.dist,ini}

**Comment by jruben4** [comment]
One of my sensors is kind of "iffy" and is sometimes not responding.  It would be nice if there was a way for your program to skip sensors that don't respond (instead of exiting the program).  

Thanks!

**Comment by ThomDietrich** [comment]
It does skip them. You can actually see that in the screengrab in the README: 

![](https://raw.githubusercontent.com/ThomDietrich/miflora-mqtt-daemon/master/demo.gif)
