### ISSUE TITLE
Support for Xiaomi Mijia Bluetooth Temperature 

### ISSUE THREAD

**Issue by robotsflo** [ThomDietrich/miflora-mqtt-daemon#51]
Hi,
Can you please add support for Xiaomi Mijia Temperature ? Or create a new " mitemp-mqtt-daemon " repository. Thanks a lot for your good job !

https://de.aliexpress.com/store/product/Neue-Original-Xiaomi-Mijia-Bluetooth-Temperatur-Luftfeuchtigkeit-Digitale-Thermometer-Feuchtigkeit-Meter-Sensor-Lcd-bildschirm-Smart-Mi/2953070_32844484376.html?spm=a2g0x.12010615.8148356.12.22227ed6B3WpL1

**Comment by uryupinsk** [comment]
Please add it as a feature, my dear friend.

**Comment by tunip** [comment]
And how do we add this as a feature? I like this project for my Mi Floras and have 6 of this MiTemp devices in the house :-).

**Comment by khzd** [comment]
+1

**Comment by cropab** [comment]
+1 there is no mijia mqtt solution for the raspberry pi.

**Comment by sendorm** [comment]
+1 to this too.

**Comment by sendorm** [comment]
> You can test this https://github.com/aqualx/miflora-mqtt-daemon/tree/mitempbt
> If test succeed I'll make PR.

I am getting this error with your code: 
`ImportError: No module named 'mitemp_bt'`

**Comment by aqualx** [comment]
_mitemp_bt_ added to requirements.txt.
So this will install all needed packages:
**sudo pip3 install -r requirements.txt**

Which MAC address has your sensor? You have sensor with screen or without? I have two of them and both start from "4C:65:A8:DB:XX:XX". In any case this is checked in _miflora-mqtt-daemon.py_ line 136...

**Comment by sendorm** [comment]
Ok I see the problem, mine is '4C:65:A8:D4:XX:XX'.
I'll try with that. 
I've also changed the poll rates to 180 times less for the mitemp while maintaining the miflora sleep times and also set the mqtt retain to true for homeassistant case. I wonder why the default is false.

**Comment by aqualx** [comment]
Ok, changed RegExp for MAC address.
What do you mean by "changed the poll rates to 180 times less for the mitemp"? Check more frequently than miflora or ...?

**Comment by sendorm** [comment]
Yes exactly. As miflora's are for plants which don't often need an update. I use the data to auto water the plants. But with these cold days, the plants are only needed to be watered each 10 days or so. So I use a sensor refresh for 180 minutes. But with the mitemp sensors which are indoors I use a sensor refresh time of 1 minute each. 

Another thing; bluepy is also needed for the mitemp.

**Comment by aqualx** [comment]
But _bluepy_ is already in _requirements.txt_
```
bluepy==1.3.0
mitemp-bt==0.0.1
```

**Comment by sendorm** [comment]
Yes you are right. I didn't check your tree's requirements.

**Comment by uryupinsk** [comment]
> Ok I see the problem, mine is '4C:65:A8:D4:XX:XX'.
> I'll try with that.
> I've also changed the poll rates to 180 times less for the mitemp while maintaining the miflora sleep times and also set the mqtt retain to true for homeassistant case. I wonder why the default is false.

Is there a possibility for the user to modify the polling rate in the config file?

**Comment by aqualx** [comment]
In config.ini there is setting:
```
[Daemon]
# The period between two measurements in seconds (Default: 300)
#period = 300
```
But for now it is used for both "Mi Flora" and "Xiaomi Mijia Bluetooth Temperature" type of devices.

**Comment by uryupinsk** [comment]
I see. Maybe could you add the possibility to have 2 different polling rates for both Mi Flora and Xiaomi Mijia Bluetooth Temperature devices?

**Comment by sendorm** [comment]
You can check my copy https://github.com/sendorm/miflora-mqtt-daemon
I have added refresh times for mijia too. It is a very crude change but works for now.

**Comment by sendorm** [comment]
You can check here for different polling rates. https://github.com/sendorm/miflora-mqtt-daemon
I copied the code from @aqualx

**Comment by aqualx** [comment]
New [commit](https://github.com/aqualx/miflora-mqtt-daemon/commit/51ad7d6320cf14faeec72fdcdf0c081f29acc0f3):
* added separate setting "period" per device type in config.ini
* switched library for 'Mijia Bluetooth Temperature Smart Humidity' from mitemp_bt to mithermometer
* fixed schema generation for openHAB
* set 'retain=True' for mqtt messages for homeassistant-mqtt
* other minor fixes

**Comment by sendorm** [comment]
It's working, thank you @aqualx.

**Comment by lionhe1966** [comment]
I am using the version by Aqualx, but after a few hours I get this error

xception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/btlewrap/bluepy.py", line 26, in _func_wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/btlewrap/bluepy.py", line 55, in connect
    self._peripheral = Peripheral(mac, iface=iface)
  File "/usr/local/lib/python3.5/dist-packages/bluepy/btle.py", line 391, in __init__
    self._connect(deviceAddr, addrType, iface)
  File "/usr/local/lib/python3.5/dist-packages/bluepy/btle.py", line 439, in _connect
    raise BTLEDisconnectError("Failed to connect to peripheral %s, addr type: %s" % (addr, addrType), rsp)
bluepy.btle.BTLEDisconnectError: Failed to connect to peripheral 4C:65:A8:D0:5E:CE, addr type: public

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/btlewrap/base.py", line 44, in __enter__
    self._backend.connect(self._mac)
  File "/usr/local/lib/python3.5/dist-packages/btlewrap/bluepy.py", line 32, in _func_wrapper
    raise BluetoothBackendException() from last_error
btlewrap.base.BluetoothBackendException

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "miflora-mqtt-daemon.py", line 508, in run
    pool_sensors(self.sensor_type, self.sensors, self.sensor_parameters)
  File "miflora-mqtt-daemon.py", line 207, in pool_sensors
    sensor['poller'].fill_cache()
  File "/usr/local/lib/python3.5/dist-packages/mithermometer/mithermometer_poller.py", line 67, in fill_cache
    with self._bt_interface.connect(self._mac) as connection:
  File "/usr/local/lib/python3.5/dist-packages/btlewrap/base.py", line 46, in __enter__
    self._lock.release()
RuntimeError: release unlocked lock

**Comment by aqualx** [comment]
There are some exceptions from calling libraries. In last commit there is a guard against them...
PS: Maybe this exceptions should be also addressed to owner. In this case [mithermometer](https://github.com/hobbypunk90/mithermometer)

**Comment by aqualx** [comment]
"Release unlocked lock" seems is now fixed directly in [blewrap](https://github.com/ChristianKuehnel/btlewrap) library on this [change](https://github.com/ChristianKuehnel/btlewrap/commit/1322d69fb321d857261c28977f230e4b5f750ed1)

**Comment by igorbljahhin** [comment]
I tried to use latest miflora-mqtt-daemon for reading Xiaomi Mijia, but I got "seems to be in the wrong format" error. Is the change mentioned in this thread merged into the master already or where I can find it?

**Comment by igorbljahhin** [comment]
> I tried to use latest miflora-mqtt-daemon for reading Xiaomi Mijia, but I got "seems to be in the wrong format" error. Is the change mentioned in this thread merged into the master already or where I can find it?

OK, I found it, it is in https://github.com/aqualx/miflora-mqtt-daemon.

**Comment by Paul-B** [comment]
> Which MAC address has your sensor? You have sensor with screen or without? I have two of them and both start from "4C:65:A8:DB:XX:XX". In any case this is checked in _miflora-mqtt-daemon.py_ line 136...
> 
> PS: section names in _config.ini_ also changed. See example at _config.ini.dist_

I had the same problem, my temperature sensor mitempbt is like this:
Tempe1 = 58:2D:34:32:xx:xx
which is not accepted and gives an error every time. As a brute force solution I commented out the mac check in miflora-mqtt-daemon.py and now it works.

**Comment by SumitBajoria** [comment]
This seems to be an epidemic. I ordered the Mijia Temperature and Humidity sensor and the MAC address is 58:2d:34:31:4b:e4. I tried commenting the mac check in miflora-mqtt-daemon.py but it did not work for me. @Paul-B can you help? What all did you comment out?

Ideally, if @ThomDietrich or @aqualx can make the necessary changes to the code so that the mac address check is either removed completely or is modified to accept 58:2D series, would be the best solution.

Thanks in advance.

**Comment by SumitBajoria** [comment]
@aqualx Will this change be sufficient or do I need to do anything else?

> # Init sensors from configuration files
> def init_sensors(sensor_type, sensors):
>     sensor_type_name = sensor_type_to_name(sensor_type)
>     if  sensor_type == sensor_type_miflora:
>         config_section = sensor_type_miflora
>         mac_regexp = "C4:7C:8D:[0-9A-F]{2}:[0-9A-F]{2}:[0-9A-F]{2}"
>     elif sensor_type == sensor_type_mitempbt:
>         config_section = sensor_type_mitempbt
>         mac_regexp = "4C:65:A8:[0-9A-F]{2}:[0-9A-F]{2}:[0-9A-F]{2}"
>     **elif sensor_type == sensor_type_mitempbt:
>         config_section = sensor_type_mitempbt
>         mac_regexp = "_58:2d:34_:[0-9A-F]{2}:[0-9A-F]{2}:[0-9A-F]{2}"**
>     else:
>         print_line('Unknown device type: {}'.format(sensor_type), error=True, sd_notify=True)
>         sys.exit(1)
> 

Help will be appreciated!

**Comment by SumitBajoria** [comment]
@aqualx I tried making the above change but I still get 
"[2019-07-21 05:28:56] The MAC address "58:2D:34:31:4B:E4" seems to be in the wrong format. Please check your configuration"

What would I need to do to get this to work? Help please!!

**Comment by SumitBajoria** [comment]
Done! I modified the miflora-mqtt-daemon.py file to include the 58:2D:34 series of MAC addresses. 

The "ValueError: Publish topic cannot contain wildcards" was because I did not edit the config.ini file properly. Tweaked that and now it seems to be working. Now to get Home Assistant to use and populate the data.

**Comment by jsponz** [comment]
@SumitBajoria Could you share the code? Thanks!

**Comment by SumitBajoria** [comment]
@jsponz Which code do you want me to share? Also, I managed to fix the miflora.service, albeit, in a very crude way.

**Comment by jsponz** [comment]
@SumitBajoria you wrote: "I modified the miflora-mqtt-daemon.py ..."

Last available version of the file is 6 months old...

**Comment by SumitBajoria** [comment]
`# Init sensors from configuration files
def init_sensors(sensor_type, sensors):
    sensor_type_name = sensor_type_to_name(sensor_type)
    if  sensor_type == sensor_type_miflora:
        config_section = sensor_type_miflora
        mac_regexp = "C4:7C:8D:[0-9A-F]{2}:[0-9A-F]{2}:[0-9A-F]{2}"
    elif sensor_type == sensor_type_mitempbt:
        config_section = sensor_type_mitempbt
        mac_regexp = "**58:2D:34:**[0-9A-F]{2}:[0-9A-F]{2}:[0-9A-F]{2}"
    else:
        print_line('Unknown device type: {}'.format(sensor_type), error=True, sd_notify=True)
        sys.exit(1)

`

**Comment by CWempe** [comment]
I enhanced the regexp and created a pull request.

https://github.com/aqualx/miflora-mqtt-daemon/pull/3

**Comment by cbugeja** [comment]
I am getting the following error:
`Initial connection to Mi Flora sensor "TemHum" (58:2D:34:32:F3:3D) failed.`
AND
`Failed to retrieve data from Mi Flora sensor "TemHum" (58:2D:34:32:F3:3D), success rate: 0%`

Any ideas how this can be solved please?

**Comment by wojciej** [comment]
Hello,
I just have purchased the new version of  Xiaomi Temperature and humidity sensor 
![IMG_3648](https://user-images.githubusercontent.com/3244472/83449502-09645580-a454-11ea-8261-5e95eaa4aaea.JPG)

It is detectable over bluetooth its Mac start with A4:C1:38.

I have tried simple approach by changing the regex at aqualux fork but this does not seems to work. 

If you could point me out to the right direction, or what kind of data should I provide to make this work that would be great.

Thanks you all who contribute to this great tool.

BR
Jarek

**Comment by AndreB81** [comment]
Hi Jarek,

issue is that this sensor is decrypted via a token. Binding the token to the miflora-mqtt-daemon is not supported by now.

BR
Andre
